name: Update dependencies

on:
  #schedule:
  #  # Run daily at 2 AM UTC
  #  - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-deps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ['master']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{ matrix.branch }}

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'

      - name: Install Python dependencies
        run: |
          python -m pip install --quiet --upgrade pip
          pip install --quiet packaging

      - name: Check for dependency updates
        id: update-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/workflows/update-dependencies.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: ${{ steps.update-check.outputs.commit-message || 'Automatic dependency update' }}
          branch: automatic-update/${{ matrix.branch }}
          delete-branch: true
          title: ${{ steps.update-check.outputs.pr-title || 'Automatic dependency update' }}
          body: ${{ steps.update-check.outputs.pr-body || 'Unable to determine updated packages' }}
          labels: update
          assignees: blast007
          reviewers: blast007
